version: "3"
services: 
    
    jupyter:
        restart: always
        build: ./services/jupyter
        environment:
            - MONGODB_URL=mongodb://mongodb:27017
            - JUPYTER_ENABLE_LAB
            - GRANT_SUDO
        volumes:
            - ./services/jupyter/certs:/etc/ssl/notebook
            - $SSHKEY_PATH:/home/jovyan/.ssh
            - $WORKSPACE_PATH:/home/jovyan/work
        ports:
            - "8888:8888"
        depends_on:
            - mongodb
        command: "start-notebook.sh --NotebookApp.password='$JUPYTER_PASSWORD' --NotebookApp.keyfile=/etc/ssl/notebook/notebook.key --NotebookApp.certfile=/etc/ssl/notebook/notebook.crt"

    mongodb:
        restart: always
        image: mongo:3.6
        environment:
            - MONGO_INITDB_ROOT_USERNAME
            - MONGO_INITDB_ROOT_PASSWORD
            - MONGO_NORMAL_USERNAME
            - MONGO_NORMAL_PASSWORD
            - MONGO_DEFAULT_DATABASE
        volumes:
            - ./services/mongodb/init_scripts:/docker-entrypoint-initdb.d
            - ./services/mongodb/mongodb.pem:/etc/ssl/mongodb.pem
            - mongodata:/data/db
        ports:
            - "27017:27017"
        command: --sslMode requireSSL --sslPEMKeyFile /etc/ssl/mongodb.pem

    cronjobs:
        restart: always
        build: ./services/cronjobs
        environment:
            - MONGO_INITDB_ROOT_USERNAME
            - MONGO_INITDB_ROOT_PASSWORD
            - TELEGRAM_CHAT_ID
            - TELEGRAM_TOKEN
        volumes:
            - $BACKUP_PATH:/backups

volumes:
    mongodata: